//KEYS Definitions

//Scan codes of cursor & special keys
//ASCII codes of box-drawing characters

#define LEFTKEY -75
#define RIGHTKEY -77
#define UPKEY -72
#define DOWNKEY -80
#define ESCKEY 27
#define TABKEY 9
#define INSKEY -82
#define DELKEY -83
#define HOMEKEY -71
#define ENDKEY -79
#define PGUPKEY -73
#define PGDNKEY -81
#define ENTERKEY 13
#define BKSPKEY 8
#define SPCKEY 32

#define F1KEY  -59
#define F2KEY  -60
#define F3KEY  -61
#define F4KEY  -62
#define F5KEY  -63
#define F6KEY  -64
#define F7KEY  -65
#define F8KEY  -66
#define F9KEY  -67
#define F10KEY -68
#define F11KEY -133
#define F12KEY -134

#define CTRLA  1
#define CTRLB  2
#define CTRLC  3
#define CTRLD  4
#define CTRLE  5
#define CTRLF  6
#define CTRLG  7
#define CTRLH  8
#define CTRLI  9
#define CTRLJ 10
#define CTRLK 11
#define CTRLL 12
#define CTRLM 13
#define CTRLN 14
#define CTRLO 15
#define CTRLP 16
#define CTRLQ 17
#define CTRLR 18
#define CTRLS 19
#define CTRLT 20
#define CTRLU 21
#define CTRLV 22
#define CTRLW 23
#define CTRLX 24
#define CTRLY 25
#define CTRLZ 26

// ASCII codes for line-drawing characters
#define TLFTCNR 218
#define TRGTCNR 191
#define BLFTCNR 192
#define BRGTCNR 217
#define LCTR   195
#define RCTR   180
#define TCTR   194
#define BCTR   193
#define CTR    197
#define HLEN   196
#define VLEN   179
#define BLOCK  177
#define SBLOCK  219

